#!/bin/sh
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

java -cp bin:lib/antlr-4.4-complete.jar WACCSemantics.WACCFrontEnd $1 < $1
exit $?
